### ISSUE TITLE
Unable to load custom TS aliases like `@/models`

### ISSUE THREAD

**Issue by kachar** [ilovepixelart/ts-migrate-mongoose#152] opened 2023-07-13 11:24 UTC
**Describe the bug**

We're trying to use the default approach with `yarn migrate up` but inside our mongoose model files we're using typescript aliases configured in the projects' `tsconfig.json` and they are not getting resolved properly since `ts-migrate-mongoose` does not know about our custom paths.

```json
// tsconfig.json

{
  "compilerOptions": {
      "target": "es2015",
      "paths": {
      "@/*": [
          "./*"
      ]
    }
  }
}
  
```

```shell
Synchronizing database with file system migrations...
Your application tried to access @, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @ (via "@/mongo/models/thread.model")
Required by: /Users/kachar/Projects/my-project/migrations/

Require stack:
- /Users/kachar/Projects/my-project/migrations/1689246892881-test-migration-1.ts
- /Users/kachar/Projects/my-project/.yarn/cache/ts-migrate-mongoose-npm-3.1.8-c236e6134e-78a9407929.zip/node_modules/ts-migrate-mongoose/dist/cjs/migrator.js
- /Users/kachar/Projects/my-project/.yarn/cache/ts-migrate-mongoose-npm-3.1.8-c236e6134e-78a9407929.zip/node_modules/ts-migrate-mongoose/dist/cjs/commander.js
- /Users/kachar/Projects/my-project/.yarn/cache/ts-migrate-mongoose-npm-3.1.8-c236e6134e-78a9407929.zip/node_modules/ts-migrate-mongoose/dist/cjs/bin.js
```

We've tried to avoid the aliases inside the models but this has many complications all over the codebase.
We've also tried to use `yarn patch` to update the `tsconfig.json` of  `ts-migrate-mongoose` but that didn't end up having any effect.

What worked for us was to have a version of `migrate.ts` in our codebase and use https://github.com/swc-project/swc-node to start it with our own `tsconfig.json` but with this approach, we can't use the CLI tool out of the box and we have to mirror the functionality.

```
"migrate:up": "node -r @swc-node/register ./migrations/index.ts up",
"migrate:down": "node -r @swc-node/register ./migrations/index.ts down",
"migrate:create": "node -r @swc-node/register ./migrations/index.ts create"
```

**Comment by ilovepixelart** [comment] 2023-07-13 12:59
Hm, yes I see the issue.. you definitely don't need to use migrate.ts directly, will think about adding this out of the box

**Comment by ilovepixelart** [comment] 2023-07-13 22:08
Add `.swcrc` to the root of your project

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2022",
    "keepClassNames": true,
    "loose": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "env": {
    "targets": {
      "node": 18
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

**Comment by kachar** [comment] 2023-07-14 13:09
@ilovepixelart Awesome! 🎉 

Having the .`swcrc` locally solves the alias problem! Thanks for the suggestion.
We've switched back to the `migrate.ts` strategy.

Maybe this can find its place in the project's readme to help others in similar situations.

Kudos for the fast reaction and support 🙇‍♂️

**Comment by ilovepixelart** [comment] 2023-07-15 07:23
PR: https://github.com/ilovepixelart/ts-migrate-mongoose/pull/157

**Comment by ilovepixelart** [comment] 2023-07-15 20:54
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.1.9

**Closed by ilovepixelart** 2023-07-15 20:54 UTC

**Comment by l-Nuril-l** [comment] 2025-01-16 23:36
> Add `.swcrc` to the root of your project example: It will tell `@swc-node/register` how to parse aliases during transpiration 
```
npx ts-migrate-mongoose down init
Synchronizing database with file system migrations...
Cannot find module '@contract'
```

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2021",
    "keepClassNames": true,
    "loose": true,
    "baseUrl": ".",
    "paths": {
      "@contract": ["node_modules/@company/interfaces"],
    }
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

I can't get alias to work with cli. Is this approach still actual?

**Comment by ilovepixelart** [comment] 2025-01-17 07:50
I Switched project to latest version of SWC register, maybe it was the cause, will check it later on my side
